### ISSUE TITLE
ViolationException発生時にLoggingSessionのfiishもerrorも呼ばれない

### ISSUE THREAD

**Issue by junsuke-fm** [koo-inc/calico#45]
https://github.com/koo-inc/calico/blob/247b05d03772134e92f01891ee6be04512ad175b/calico-servlet/src/main/java/jp/co/freemind/calico/servlet/RequestSession.java#L71-L75

ViolationException時にaccess_end_logを書き込むタイミングが無い。

1. ViolationExceptionの時はfinishを呼ぶ。（statusCodeどうする？）
2. ViolationException時でもerror呼ぶ、ViolationExceptionやからどうするかとかはerrorの中でやってね。

うーん、2案の方が良い気もせんでもないが・・
どう思う？

**Comment by tasuku-s** [comment]
2がよさそうです！

**Comment by junsuke-fm** [comment]
よろ！
